# schedule in cron format. This example runs every 5 minutes.
# cron: minute, hour, day of month, month, day of week
# * = any value
# */x = every x units

schedule: '*/5 * * * *'
tag: 'hello-world:latest'
github_repo: 'https://example.com'
github_branch: 'master'
